name: Build and deploy Umami to Azure Web App - umamidev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

    - name: Build the application
      run: yarn build

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: umami-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: umami-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B8CC4608C43D4EA8AE0B94DEC16E7BEC }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_89458E72879643BDB04DCE4AC3592434 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2189C00EE0BF4DBE891EC876B3A3A2C5 }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'umamidev'
        slot-name: 'Production'
        package: .

    - name: 'Configure startup command'
      uses: azure/appservice-settings@v1
      with:
        app-name: 'umamidev'
        app-settings-json: '[{"name": "WEBSITE_RUN_FROM_PACKAGE", "value": "0"}, {"name": "WEBSITE_NODE_DEFAULT_VERSION", "value": "~20"}, {"name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true"}]'
        startup-command: 'yarn start'
